export const DEFAULT_MIN_TIME_STEP = 0.0;
export const DEFAULT_TIME_STEP = 0.5;
export const DEFAULT_MAX_TIME_STEP = 2.0;
export const DEFAULT_TIME_STEP_STEP = 0.1;

export const DEFAULT_DIFFUSION = 0.5;
export const DEFAULT_MIN_DIFFUSION = 0.0;
export const DEFAULT_MAX_DIFFUSION = 2.0;
export const DEFAULT_DIFFUSION_STEP = 0.1;

export const DEFAULT_ADDED_DENSITY = 5;
export const DEFAULT_ADDED_DENSITY_MIN = 0;
export const DEFAULT_ADDED_DENSITY_MAX = 40;
export const DEFAULT_ADDED_DENSITY_STEP = 1;

export const DEFAULT_ADDED_VELOCITY = 50;
export const DEFAULT_ADDED_VELOCITY_MIN = 0;
export const DEFAULT_ADDED_VELOCITY_MAX = 500;
export const DEFAULT_ADDED_VELOCITY_STEP = 50;
